import 'package:flutter/material.dart';
import 'package:fontsize_check_app/component/text_number_item.dart';

class TextNumberItemList extends StatelessWidget {
  const TextNumberItemList({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: const [
        TextNumberItem(fontSize: 1, text: '1'),
        TextNumberItem(fontSize: 2, text: '2'),
        TextNumberItem(fontSize: 3, text: '3'),
        TextNumberItem(fontSize: 4, text: '4'),
        TextNumberItem(fontSize: 5, text: '5'),
        TextNumberItem(fontSize: 6, text: '6'),
        TextNumberItem(fontSize: 7, text: '7'),
        TextNumberItem(fontSize: 8, text: '8'),
        TextNumberItem(fontSize: 9, text: '9'),
        TextNumberItem(fontSize: 10, text: '10'),
        TextNumberItem(fontSize: 11, text: '11'),
        TextNumberItem(fontSize: 12, text: '12'),
        TextNumberItem(fontSize: 13, text: '13'),
        TextNumberItem(fontSize: 14, text: '14'),
        TextNumberItem(fontSize: 15, text: '15'),
        TextNumberItem(fontSize: 16, text: '16'),
        TextNumberItem(fontSize: 17, text: '17'),
        TextNumberItem(fontSize: 18, text: '18'),
        TextNumberItem(fontSize: 19, text: '19'),
        TextNumberItem(fontSize: 20, text: '20'),
        TextNumberItem(fontSize: 21, text: '21'),
        TextNumberItem(fontSize: 22, text: '22'),
        TextNumberItem(fontSize: 23, text: '23'),
        TextNumberItem(fontSize: 24, text: '24'),
        TextNumberItem(fontSize: 25, text: '25'),
        TextNumberItem(fontSize: 26, text: '26'),
        TextNumberItem(fontSize: 27, text: '27'),
        TextNumberItem(fontSize: 28, text: '28'),
        TextNumberItem(fontSize: 29, text: '29'),
        TextNumberItem(fontSize: 30, text: '30'),
        TextNumberItem(fontSize: 31, text: '31'),
        TextNumberItem(fontSize: 32, text: '32'),
        TextNumberItem(fontSize: 33, text: '33'),
        TextNumberItem(fontSize: 34, text: '34'),
        TextNumberItem(fontSize: 35, text: '35'),
        TextNumberItem(fontSize: 36, text: '36'),
        TextNumberItem(fontSize: 37, text: '37'),
        TextNumberItem(fontSize: 38, text: '38'),
        TextNumberItem(fontSize: 39, text: '39'),
        TextNumberItem(fontSize: 40, text: '40'),
        TextNumberItem(fontSize: 41, text: '41'),
        TextNumberItem(fontSize: 42, text: '42'),
        TextNumberItem(fontSize: 43, text: '43'),
        TextNumberItem(fontSize: 44, text: '44'),
        TextNumberItem(fontSize: 45, text: '45'),
        TextNumberItem(fontSize: 46, text: '46'),
        TextNumberItem(fontSize: 47, text: '47'),
        TextNumberItem(fontSize: 48, text: '48'),
        TextNumberItem(fontSize: 49, text: '49'),
        TextNumberItem(fontSize: 50, text: '50'),
        TextNumberItem(fontSize: 51, text: '51'),
        TextNumberItem(fontSize: 52, text: '52'),
        TextNumberItem(fontSize: 53, text: '53'),
        TextNumberItem(fontSize: 54, text: '54'),
        TextNumberItem(fontSize: 55, text: '55'),
        TextNumberItem(fontSize: 56, text: '56'),
        TextNumberItem(fontSize: 57, text: '57'),
        TextNumberItem(fontSize: 58, text: '58'),
        TextNumberItem(fontSize: 59, text: '59'),
        TextNumberItem(fontSize: 60, text: '60'),
        TextNumberItem(fontSize: 61, text: '61'),
        TextNumberItem(fontSize: 62, text: '62'),
        TextNumberItem(fontSize: 63, text: '63'),
        TextNumberItem(fontSize: 64, text: '64'),
        TextNumberItem(fontSize: 65, text: '65'),
        TextNumberItem(fontSize: 66, text: '66'),
        TextNumberItem(fontSize: 67, text: '67'),
        TextNumberItem(fontSize: 68, text: '68'),
        TextNumberItem(fontSize: 69, text: '69'),
        TextNumberItem(fontSize: 70, text: '70'),
        TextNumberItem(fontSize: 71, text: '71'),
        TextNumberItem(fontSize: 72, text: '72'),
        TextNumberItem(fontSize: 73, text: '73'),
        TextNumberItem(fontSize: 74, text: '74'),
        TextNumberItem(fontSize: 75, text: '75'),
        TextNumberItem(fontSize: 76, text: '76'),
        TextNumberItem(fontSize: 77, text: '77'),
        TextNumberItem(fontSize: 78, text: '78'),
        TextNumberItem(fontSize: 79, text: '79'),
        TextNumberItem(fontSize: 80, text: '80'),
        TextNumberItem(fontSize: 81, text: '81'),
        TextNumberItem(fontSize: 82, text: '82'),
        TextNumberItem(fontSize: 83, text: '83'),
        TextNumberItem(fontSize: 84, text: '84'),
        TextNumberItem(fontSize: 85, text: '85'),
        TextNumberItem(fontSize: 86, text: '86'),
        TextNumberItem(fontSize: 87, text: '87'),
        TextNumberItem(fontSize: 88, text: '88'),
        TextNumberItem(fontSize: 89, text: '89'),
        TextNumberItem(fontSize: 90, text: '90'),
        TextNumberItem(fontSize: 91, text: '91'),
        TextNumberItem(fontSize: 92, text: '92'),
        TextNumberItem(fontSize: 93, text: '93'),
        TextNumberItem(fontSize: 94, text: '94'),
        TextNumberItem(fontSize: 95, text: '95'),
        TextNumberItem(fontSize: 96, text: '96'),
        TextNumberItem(fontSize: 97, text: '97'),
        TextNumberItem(fontSize: 98, text: '98'),
        TextNumberItem(fontSize: 99, text: '99'),
        TextNumberItem(fontSize: 100, text: '100'),
      ],
    );
  }
}
